# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

linpredcompute <- function(X, nsites, p, beta, offset) {
    .Call('CARBayesST_linpredcompute', PACKAGE = 'CARBayesST', X, nsites, p, beta, offset)
}

quadform <- function(W_duplet1, W_duplet2, n_duplet, nsites, phi, nneighbours, diagonal, offdiagonal) {
    .Call('CARBayesST_quadform', PACKAGE = 'CARBayesST', W_duplet1, W_duplet2, n_duplet, nsites, phi, nneighbours, diagonal, offdiagonal)
}

poissoncarupdate <- function(W_list, nsites, phi, tau2, y, phi_tune, rho_num, rho_den, offset) {
    .Call('CARBayesST_poissoncarupdate', PACKAGE = 'CARBayesST', W_list, nsites, phi, tau2, y, phi_tune, rho_num, rho_den, offset)
}

poissonindepupdate <- function(nsites, theta, tau2, y, theta_tune, offset) {
    .Call('CARBayesST_poissonindepupdate', PACKAGE = 'CARBayesST', nsites, theta, tau2, y, theta_tune, offset)
}

poissonbetaupdate <- function(X, nsites, p, beta, proposal, offset, y, prior_meanbeta, prior_varbeta) {
    .Call('CARBayesST_poissonbetaupdate', PACKAGE = 'CARBayesST', X, nsites, p, beta, proposal, offset, y, prior_meanbeta, prior_varbeta)
}

Zupdate <- function(Z, Offset, Y, alpha, lambda, nsites, ntime, G, SS, Gstar) {
    .Call('CARBayesST_Zupdate', PACKAGE = 'CARBayesST', Z, Offset, Y, alpha, lambda, nsites, ntime, G, SS, Gstar)
}

alphaupdate <- function(Z, nsites, logratio, ntime) {
    .Call('CARBayesST_alphaupdate', PACKAGE = 'CARBayesST', Z, nsites, logratio, ntime)
}

Xupdate <- function(Wspace, Y, offset, K, N, X, tau2, proposalsdX) {
    .Call('CARBayesST_Xupdate', PACKAGE = 'CARBayesST', Wspace, Y, offset, K, N, X, tau2, proposalsdX)
}

